config/routes.rb
Rails.application.routes.draw do
  root 'formats#index'

  get '/preview' => 'preview#index'
  post '/preview/download' => 'preview#download'
  get '/preview/sample' => 'preview#sample'

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # This needs to be at the end of the file in order to not override any custom routes
  resources :formats
  resources :users
  resources :preview

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/format.rb
# Format holds a JSON data specification file
class Format < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :attachment

  mount_uploader(:attachment, AttachmentUploader)
end

app/controllers/formats_controller.rb
# Handles CRUD Operations and Upload for Format specifications
# noinspection ALL
class FormatsController < ApplicationController
  # noinspection RailsParamDefResolve
  before_action :authenticate_user!, except: %i[index show]

  def index
    @formats = Format.all
  end

  def show
    @format = Format.find(params[:id])
    @json = []
    begin
      JSON.parse(helpers.read_attachment(@format))['vars'].each { |k, v|
        @json << { 'Name' => k, 'Position' => v['position'], 'Type' => v['type'], 'Missings' => v['missings'], 'Truthy Values' => v['true_values']}
      }
    rescue
      # resolved because empty @json will be handled in view
    end
  end

  def new
    @format = Format.new
    @format_id = @format.id.to_i
  end

  def edit
    @format = Format.find(params[:id])
    @json = helpers.read_attachment(@format)
    @json = '{}' unless @json.present?
  end

  def create
    @format = Format.new(format_params)
    if @format.save
      flash[:notice] = "Created successfully"
      redirect_to '/formats'
    else
      render action: :new
    end
  end

  def update
    @format = Format.find(params[:id])
    @json = helpers.read_attachment(@format)
    if update_format(@format, params[:json])
      flash[:notice] = 'Edited successfully'
      redirect_to '/formats'
    else
      render action: :edit
    end
  end

  def destroy
    @format = Format.find(params[:id])
    @format.destroy
    flash[:notice] = 'Deleted successfully'
    redirect_to '/formats'
  end

  private

  def update_format(format, json)
    helpers.update_attachment(format, json) && format.update(format_params)
  end

  def format_params
    params.require(:format).permit(:title, :attachment)
  end
end

app/views/formats/edit.html.erb
<% javascript_include_tag "formats" %>

<script>
  $(document).ready(function () {
      window.json = <%= @json.html_safe %>;
      formats.setup();
  });
</script>

<div class="container">
  <h1>Edit Format</h1>

  <div id="error_explanation" class="alert alert-danger" hidden>
    <div class="error-header"></div>
    <ul id="error-list"></ul>
  </div>

  <%= simple_form_for @format, id: "editFormat" do |f| %>
    <%= f.input :title %>

    <%= hidden_field_tag(:json, '') %>

    <div class="container" id="json_editor" style="height: 400px;"></div>

    <div>
      <br>
      <%= link_to ' Cancel', "/formats", class: "btn btn-outline-primary fas fa-angle-left" %>
      <%= f.submit "Update", class: "btn btn-primary fas", id: "submit_edit_button" %>
    </div>
  <% end %>
</div>

app/views/formats/index.html.erb
<h1>Formats</h1>

<% if signed_in? && @formats.empty? -%>
  You are logged in. There are no formats yet. Start creating some by pressing "Create Format". Afterwards there will also be the Preview available!
  <br/>
<% end -%>

<% unless @formats.empty? %>
  <table class="table table-striped">
    <thead class="thead-dark">
    <tr>
      <th>Title</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @formats.each do |format| %>
      <tr>
        <td><%= link_to format.title, format_path(format) %></td>
        <td align="right"><%= link_to ' Edit', edit_format_path(format),
                        class: "btn btn-sm btn-outline-primary fa fa-edit" if signed_in? %>
          <%= link_to ' Delete', format_path(format),
                        method: :delete,
                        data: { confirm: 'Are you sure?' },
                        class: "btn btn-sm btn-outline-primary fa fa-trash" if signed_in? %>
        <%= link_to ' Preview', "preview?format_id=#{format.id}",
                    class: "btn btn-sm btn-outline-primary fa fa-eye" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end -%>

<div>
  <br>
  <%= link_to ' Create Format', "formats/new",
              class: "btn btn-primary fa fa-plus" if signed_in? %>
</div>

app/views/formats/new.html.erb
<div class="container">
  <h1>Create Format</h1>

  <%= simple_form_for @format do |f| %>

    <% if @format.errors.any?%>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@format.errors.count, "error") %>
          prohibited this format from being saved:
        </h2>

        <ul>
          <% @format.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <%= f.input :title%>


    <h3>Upload File</h3>
    <% if @format.attachment.file.nil? -%>

      <%= f.input :attachment, label: false%>
    <% else %>
      File already uploaded: <%= @upload_name %>
      <%= link_to 'Delete', @upload, method: :delete, data: {confirm: 'Are you sure?'} %>
    <% end %>

    <footer>
      <%= link_to ' Cancel', "/formats", class: "btn btn-outline-primary fas fa-angle-left" %>
      <%= f.submit "Create", class: "btn btn-primary fas", :"data-turbolinks" => false%>
    </footer>
  <% end %>

</div>

app/views/formats/show.html.erb
<script>
    $(document).ready(function () {
        createErrorMessages();
    });

    function  createErrorMessages() {
        var listContents = [];

        listContents.push("The File is missing or could not be read.");

        $('.error-header')[0].textContent = "JSON could not be shown:";
        makeList(listContents);

        $('#error_explanation').removeAttr('hidden');
    }

    function makeList(array) {
        // Create the list element:
        var list = document.getElementById('error-list');
        $('#error-list').empty();

        for(var i = 0; i < array.length; i++) {
            // Create the list item:
            var item = document.createElement('li');

            // Set its contents:
            item.appendChild(document.createTextNode(array[i]));

            // Add it to the list:
            list.appendChild(item);
        }

        // Finally, return the constructed list:
        return list;
    }
</script>

<h1>Format</h1>

<% if @json.to_s == '[]' -%>
  <div id="error_explanation" class="alert alert-danger">
    <div class="error-header"></div>
    <ul id="error-list">
    </ul>
  </div>
<% end %>
<p>
  <strong>Title:</strong>
  <%= @format.title %>
</p>

<p>
  <strong>Date of Creation:</strong>
  <%= @format.created_at %>
</p>

<% if @json.to_s != '[]' -%>
  <%= link_to " Download Specification", @format.attachment_url, download: @format.title, class: "btn btn-outline-primary fas fa-download" %>

  <p class="table">
  <h3>Contents</h3>
  <div id="outputdiv" class="table table-striped mono"><%= build_table(@json).html_safe %></div>
  </p>
<% end %>

<p>
  <%= link_to ' Back', "/formats", class: "btn btn-outline-primary fas fa-angle-left"%>
</p>